//go:build !ignore_autogenerated

/*
Copyright 2025 Scality.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCRL) DeepCopyInto(out *ManagedCRL) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCRL.
func (in *ManagedCRL) DeepCopy() *ManagedCRL {
	if in == nil {
		return nil
	}
	out := new(ManagedCRL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCRL) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCRLList) DeepCopyInto(out *ManagedCRLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedCRL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCRLList.
func (in *ManagedCRLList) DeepCopy() *ManagedCRLList {
	if in == nil {
		return nil
	}
	out := new(ManagedCRLList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCRLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCRLSpec) DeepCopyInto(out *ManagedCRLSpec) {
	*out = *in
	in.IssuerRef.DeepCopyInto(&out.IssuerRef)
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Revocations != nil {
		in, out := &in.Revocations, &out.Revocations
		*out = make([]RevocationSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCRLSpec.
func (in *ManagedCRLSpec) DeepCopy() *ManagedCRLSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedCRLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCRLStatus) DeepCopyInto(out *ManagedCRLStatus) {
	*out = *in
	if in.SecretReady != nil {
		in, out := &in.SecretReady, &out.SecretReady
		*out = new(bool)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.CRLValidUntil.DeepCopyInto(&out.CRLValidUntil)
	if in.ObservedCASecretRef != nil {
		in, out := &in.ObservedCASecretRef, &out.ObservedCASecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCRLStatus.
func (in *ManagedCRLStatus) DeepCopy() *ManagedCRLStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedCRLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RevocationSpec) DeepCopyInto(out *RevocationSpec) {
	*out = *in
	if in.RevocationTime != nil {
		in, out := &in.RevocationTime, &out.RevocationTime
		*out = (*in).DeepCopy()
	}
	if in.ReasonCode != nil {
		in, out := &in.ReasonCode, &out.ReasonCode
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RevocationSpec.
func (in *RevocationSpec) DeepCopy() *RevocationSpec {
	if in == nil {
		return nil
	}
	out := new(RevocationSpec)
	in.DeepCopyInto(out)
	return out
}
